"""Phone and location presets for realistic video metadata."""

from __future__ import annotations

# (lat, lon, altitude_m) — city centers / landmarks
LOCATIONS: dict[str, dict] = {
    "sk-bratislava": {
        "name": "Bratislava, Slovakia",
        "country": "Slovakia",
        "country_code": "SK",
        "city": "Bratislava",
        "lat": 48.1486,
        "lon": 17.1077,
        "alt": 152.0,
    },
    "sk-kosice": {
        "name": "Košice, Slovakia",
        "country": "Slovakia",
        "country_code": "SK",
        "city": "Košice",
        "lat": 48.7164,
        "lon": 21.2611,
        "alt": 208.0,
    },
    "cz-prague": {
        "name": "Prague, Czech Republic",
        "country": "Czech Republic",
        "country_code": "CZ",
        "city": "Prague",
        "lat": 50.0755,
        "lon": 14.4378,
        "alt": 235.0,
    },
    "at-vienna": {
        "name": "Vienna, Austria",
        "country": "Austria",
        "country_code": "AT",
        "city": "Vienna",
        "lat": 48.2082,
        "lon": 16.3738,
        "alt": 171.0,
    },
    "hu-budapest": {
        "name": "Budapest, Hungary",
        "country": "Hungary",
        "country_code": "HU",
        "city": "Budapest",
        "lat": 47.4979,
        "lon": 19.0402,
        "alt": 102.0,
    },
    "pl-warsaw": {
        "name": "Warsaw, Poland",
        "country": "Poland",
        "country_code": "PL",
        "city": "Warsaw",
        "lat": 52.2297,
        "lon": 21.0122,
        "alt": 100.0,
    },
    "de-berlin": {
        "name": "Berlin, Germany",
        "country": "Germany",
        "country_code": "DE",
        "city": "Berlin",
        "lat": 52.5200,
        "lon": 13.4050,
        "alt": 34.0,
    },
    "uk-london": {
        "name": "London, United Kingdom",
        "country": "United Kingdom",
        "country_code": "GB",
        "city": "London",
        "lat": 51.5074,
        "lon": -0.1278,
        "alt": 11.0,
    },
    "us-nyc": {
        "name": "New York, USA",
        "country": "United States",
        "country_code": "US",
        "city": "New York",
        "lat": 40.7128,
        "lon": -74.0060,
        "alt": 10.0,
    },
    "us-la": {
        "name": "Los Angeles, USA",
        "country": "United States",
        "country_code": "US",
        "city": "Los Angeles",
        "lat": 34.0522,
        "lon": -118.2437,
        "alt": 71.0,
    },
    "es-barcelona": {
        "name": "Barcelona, Spain",
        "country": "Spain",
        "country_code": "ES",
        "city": "Barcelona",
        "lat": 41.3874,
        "lon": 2.1686,
        "alt": 12.0,
    },
    "it-rome": {
        "name": "Rome, Italy",
        "country": "Italy",
        "country_code": "IT",
        "city": "Rome",
        "lat": 41.9028,
        "lon": 12.4964,
        "alt": 21.0,
    },
    "fr-paris": {
        "name": "Paris, France",
        "country": "France",
        "country_code": "FR",
        "city": "Paris",
        "lat": 48.8566,
        "lon": 2.3522,
        "alt": 35.0,
    },
}

# Realistic device fingerprints for QuickTime / MP4
PHONES: dict[str, dict] = {
    # Apple
    "iphone-16-pro-max": {
        "make": "Apple",
        "model": "iPhone 16 Pro Max",
        "software": "18.3.1",
        "lens": "iPhone 16 Pro Max back camera 6.86mm f/1.78",
        "vendor": "Apple",
    },
    "iphone-16-pro": {
        "make": "Apple",
        "model": "iPhone 16 Pro",
        "software": "18.3.1",
        "lens": "iPhone 16 Pro back camera 6.86mm f/1.78",
        "vendor": "Apple",
    },
    "iphone-16": {
        "make": "Apple",
        "model": "iPhone 16",
        "software": "18.2",
        "lens": "iPhone 16 back camera 6.86mm f/1.6",
        "vendor": "Apple",
    },
    "iphone-16-plus": {
        "make": "Apple",
        "model": "iPhone 16 Plus",
        "software": "18.2",
        "lens": "iPhone 16 Plus back camera 6.86mm f/1.6",
        "vendor": "Apple",
    },
    "iphone-15-pro-max": {
        "make": "Apple",
        "model": "iPhone 15 Pro Max",
        "software": "18.1.1",
        "lens": "iPhone 15 Pro Max back camera 6.86mm f/1.78",
        "vendor": "Apple",
    },
    "iphone-15-pro": {
        "make": "Apple",
        "model": "iPhone 15 Pro",
        "software": "18.1.1",
        "lens": "iPhone 15 Pro back camera 6.86mm f/1.78",
        "vendor": "Apple",
    },
    "iphone-15": {
        "make": "Apple",
        "model": "iPhone 15",
        "software": "18.0",
        "lens": "iPhone 15 back camera 6.86mm f/1.6",
        "vendor": "Apple",
    },
    "iphone-15-plus": {
        "make": "Apple",
        "model": "iPhone 15 Plus",
        "software": "18.0",
        "lens": "iPhone 15 Plus back camera 6.86mm f/1.6",
        "vendor": "Apple",
    },
    "iphone-14-pro-max": {
        "make": "Apple",
        "model": "iPhone 14 Pro Max",
        "software": "17.6.1",
        "lens": "iPhone 14 Pro Max back camera 6.86mm f/1.78",
        "vendor": "Apple",
    },
    "iphone-14-pro": {
        "make": "Apple",
        "model": "iPhone 14 Pro",
        "software": "17.5.1",
        "lens": "iPhone 14 Pro back camera 6.86mm f/1.78",
        "vendor": "Apple",
    },
    "iphone-14": {
        "make": "Apple",
        "model": "iPhone 14",
        "software": "17.5",
        "lens": "iPhone 14 back camera 5.7mm f/1.5",
        "vendor": "Apple",
    },
    "iphone-13-pro": {
        "make": "Apple",
        "model": "iPhone 13 Pro",
        "software": "17.4.1",
        "lens": "iPhone 13 Pro back camera 5.7mm f/1.5",
        "vendor": "Apple",
    },
    "iphone-13": {
        "make": "Apple",
        "model": "iPhone 13",
        "software": "17.4",
        "lens": "iPhone 13 back camera 5.1mm f/1.6",
        "vendor": "Apple",
    },
    "iphone-13-mini": {
        "make": "Apple",
        "model": "iPhone 13 mini",
        "software": "17.3",
        "lens": "iPhone 13 mini back camera 5.1mm f/1.6",
        "vendor": "Apple",
    },
    "iphone-12-pro": {
        "make": "Apple",
        "model": "iPhone 12 Pro",
        "software": "16.7.5",
        "lens": "iPhone 12 Pro back camera 4.2mm f/1.6",
        "vendor": "Apple",
    },
    "iphone-12": {
        "make": "Apple",
        "model": "iPhone 12",
        "software": "16.7.5",
        "lens": "iPhone 12 back camera 4.2mm f/1.6",
        "vendor": "Apple",
    },
    "iphone-11-pro": {
        "make": "Apple",
        "model": "iPhone 11 Pro",
        "software": "16.6",
        "lens": "iPhone 11 Pro back camera 4.25mm f/1.8",
        "vendor": "Apple",
    },
    "iphone-11": {
        "make": "Apple",
        "model": "iPhone 11",
        "software": "16.6",
        "lens": "iPhone 11 back camera 4.25mm f/1.8",
        "vendor": "Apple",
    },
    "iphone-se-3": {
        "make": "Apple",
        "model": "iPhone SE (3rd generation)",
        "software": "17.4",
        "lens": "iPhone SE (3rd generation) back camera 3.99mm f/1.8",
        "vendor": "Apple",
        "display_name": "Apple iPhone SE (2022)",
    },
    # Samsung
    "samsung-s25-ultra": {
        "make": "samsung",
        "model": "SM-S938B",
        "software": "S938BXXU1AYA1",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy S25 Ultra",
    },
    "samsung-s25": {
        "make": "samsung",
        "model": "SM-S931B",
        "software": "S931BXXU1AYA1",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy S25",
    },
    "samsung-s24-ultra": {
        "make": "samsung",
        "model": "SM-S928B",
        "software": "S928BXXU4AXK4",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy S24 Ultra",
    },
    "samsung-s24": {
        "make": "samsung",
        "model": "SM-S921B",
        "software": "S921BXXU1AXCG",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy S24",
    },
    "samsung-s23-ultra": {
        "make": "samsung",
        "model": "SM-S918B",
        "software": "S918BXXU7CXK4",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy S23 Ultra",
    },
    "samsung-s23": {
        "make": "samsung",
        "model": "SM-S911B",
        "software": "S911BXXU3CWK1",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy S23",
    },
    "samsung-s22": {
        "make": "samsung",
        "model": "SM-S901B",
        "software": "S901BXXU8CXK4",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy S22",
    },
    "samsung-zflip6": {
        "make": "samsung",
        "model": "SM-F741B",
        "software": "F741BXXU2AXK4",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy Z Flip6",
    },
    "samsung-a55": {
        "make": "samsung",
        "model": "SM-A556B",
        "software": "A556BXXU5AXK4",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy A55",
    },
    "samsung-a54": {
        "make": "samsung",
        "model": "SM-A546B",
        "software": "A546BXXU9CWL1",
        "lens": None,
        "vendor": "Samsung",
        "display_name": "Samsung Galaxy A54",
    },
    # Google
    "pixel-9-pro": {
        "make": "Google",
        "model": "Pixel 9 Pro",
        "software": "AD1A.240905.004",
        "lens": None,
        "vendor": "Google",
    },
    "pixel-9": {
        "make": "Google",
        "model": "Pixel 9",
        "software": "AD1A.240905.004",
        "lens": None,
        "vendor": "Google",
    },
    "pixel-8-pro": {
        "make": "Google",
        "model": "Pixel 8 Pro",
        "software": "AP2A.240905.003",
        "lens": None,
        "vendor": "Google",
    },
    "pixel-8": {
        "make": "Google",
        "model": "Pixel 8",
        "software": "AP2A.240905.003",
        "lens": None,
        "vendor": "Google",
    },
    "pixel-7-pro": {
        "make": "Google",
        "model": "Pixel 7 Pro",
        "software": "TQ3A.230805.001",
        "lens": None,
        "vendor": "Google",
    },
    "pixel-7": {
        "make": "Google",
        "model": "Pixel 7",
        "software": "TQ3A.230805.001",
        "lens": None,
        "vendor": "Google",
    },
    "pixel-6a": {
        "make": "Google",
        "model": "Pixel 6a",
        "software": "TQ3A.230805.001",
        "lens": None,
        "vendor": "Google",
    },
    # Xiaomi / Redmi
    "xiaomi-14-ultra": {
        "make": "Xiaomi",
        "model": "24030PN60G",
        "software": "UKQ1.240523.001",
        "lens": None,
        "vendor": "Xiaomi",
        "display_name": "Xiaomi 14 Ultra",
    },
    "xiaomi-14": {
        "make": "Xiaomi",
        "model": "23127PN0CG",
        "software": "UKQ1.230804.001",
        "lens": None,
        "vendor": "Xiaomi",
        "display_name": "Xiaomi 14",
    },
    "xiaomi-13": {
        "make": "Xiaomi",
        "model": "2211133G",
        "software": "TKQ1.220905.001",
        "lens": None,
        "vendor": "Xiaomi",
        "display_name": "Xiaomi 13",
    },
    "redmi-note-13": {
        "make": "Xiaomi",
        "model": "2312DRA50G",
        "software": "UKQ1.230917.001",
        "lens": None,
        "vendor": "Xiaomi",
        "display_name": "Redmi Note 13",
    },
    # OnePlus / Nothing / Huawei / Oppo
    "oneplus-12": {
        "make": "OnePlus",
        "model": "CPH2581",
        "software": "CPH2581_14.0.0.600",
        "lens": None,
        "vendor": "OnePlus",
        "display_name": "OnePlus 12",
    },
    "oneplus-11": {
        "make": "OnePlus",
        "model": "CPH2449",
        "software": "CPH2449_14.0.0.500",
        "lens": None,
        "vendor": "OnePlus",
        "display_name": "OnePlus 11",
    },
    "nothing-phone-2": {
        "make": "Nothing",
        "model": "A065",
        "software": "A065_3.0",
        "lens": None,
        "vendor": "Nothing",
        "display_name": "Nothing Phone (2)",
    },
    "nothing-phone-2a": {
        "make": "Nothing",
        "model": "A142",
        "software": "A142_2.5",
        "lens": None,
        "vendor": "Nothing",
        "display_name": "Nothing Phone (2a)",
    },
    "huawei-p60-pro": {
        "make": "HUAWEI",
        "model": "ALN-L29",
        "software": "ALN-L29 12.0.0.260",
        "lens": None,
        "vendor": "HUAWEI",
        "display_name": "Huawei P60 Pro",
    },
    "oppo-find-x7": {
        "make": "OPPO",
        "model": "CPH2585",
        "software": "CPH2585_14.0.0.800",
        "lens": None,
        "vendor": "OPPO",
        "display_name": "OPPO Find X7",
    },
    "sony-xperia-1-v": {
        "make": "Sony",
        "model": "XQ-DQ72",
        "software": "69.0.A.2.50",
        "lens": None,
        "vendor": "Sony",
        "display_name": "Sony Xperia 1 V",
    },
}


def list_phones() -> list[tuple[str, str]]:
    rows = []
    for key, p in PHONES.items():
        label = p.get("display_name") or f"{p['make']} {p['model']}"
        rows.append((key, label))
    return rows


def list_locations() -> list[tuple[str, str]]:
    return [(key, loc["name"]) for key, loc in LOCATIONS.items()]
